version = 0.1

[default.deploy.parameters]
stack_name = "trashbox-api"
resolve_s3 = true
s3_prefix = "trashbox-api"
region = "ap-southeast-1"
profile = "trashbox"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SageMakerEndpoint=\"pytorch-inference-2025-09-21-04-47-50-968\""
image_repositories = []
